### ISSUE TITLE
Linear operator

### ISSUE THREAD

**Issue by santiagoropb** [andrenarchy/krypy#65] opened 2019-02-18 21:33 UTC
Is there an example on how to build a LinearOperator from scipy and use it with one of the Krylov solvers? When I use a perfectly valid LinearOperator from scipy with Gmres I get the following error:

File "/Users/santiago/Software/miniconda3/envs/pymumps/lib/python3.6/site-packages/krypy/linsys.py", line 113, in __init__
    self.Mlb = self.Ml*self.b
  File "/Users/santiago/Software/miniconda3/envs/pymumps/lib/python3.6/site-packages/krypy/utils.py", line 1379, in __mul__
    return self.dot(X)
  File "/Users/santiago/Software/miniconda3/envs/pymumps/lib/python3.6/site-packages/krypy/utils.py", line 1351, in dot
    return self._dot(X)
  File "/Users/santiago/Software/miniconda3/envs/pymumps/lib/python3.6/site-packages/scipy/sparse/linalg/interface.py", line 232, in matvec
    y = y.reshape(M,1)

With Scipy the LinearOperator works fine tho.

**Comment by andrenarchy** [comment] 2019-02-22 19:53
KryPy currently uses its own implementation of `LinearOperator` but it should work fine with scipy's. There's a conversion happening here: https://github.com/andrenarchy/krypy/blob/master/krypy/utils.py#L219

Can you post the code?

**Comment by santiagoropb** [comment] 2019-02-25 18:09
I tried to write a simple example where I am seeing the issue. I basically create a scipy operator from a list of Scipy matrices. The only thing I overload is the matrix-vector product. When I run the operator with scipy it works but when I pass it to Gmres from Krypy it complains about shape. I appreciate any insights

from scipy.sparse.linalg.interface import LinearOperator
from scipy.sparse.linalg import spsolve
from scipy.sparse.linalg import gmres as sp_gmres
from scipy.sparse import coo_matrix, identity, bmat
from scipy.stats import ortho_group
from krypy.linsys import LinearSystem, Gmres
import numpy as np
np.random.seed(seed=985739465)


class MatrixOperator(LinearOperator):

    def __init__(self, D, c, A, B, rho=1.0):
        self.__rho = rho
        self.__G, self.__M, self.__N, self.__b = build_fixed_point_matrices(D, c, A, B, rho)
        self.__nu = self.__G.shape[1]
        super(MatrixOperator, self).__init__(dtype=np.float, shape=(self.__nu, self.__nu))
        self.__u0 = np.zeros(self.__nu)
        uk = np.zeros(self.__nu)
        uk = self.__G.dot(uk) + self.__b
        self.__T0 = uk
        self.myrhs = self.__u0 - self.__T0

    def _matvec(self, h):
        Tk = self.__u0 + h
        Tk = self.__G.dot(Tk) + self.__b
        delta_u = h - (Tk-self.__T0)
        return delta_u


def generate_svd(n, m, k, symmetric=False):

    if n >= m:
        O = ortho_group.rvs(dim=n)
        U = O[0:n, 0:m]
        d = np.random.lognormal(mean=0.0, sigma=k, size=m)
        S = np.diag(d)
        if symmetric and n == m:
            return U, S, U
        V = ortho_group.rvs(dim=m)
        return U, S, V
    else:
        U = ortho_group.rvs(dim=n)
        d = np.random.lognormal(mean=0.0, sigma=k, size=n)
        S = np.zeros((n, m))
        for i in range(n):
            S[i, i] = d[i]
        V = ortho_group.rvs(dim=m)
        return U, S, V


def generate_random_matrix(m, n, s, symmetric=False):
    Ud, Sd, Vd = generate_svd(m, n, s, symmetric=symmetric)
    return coo_matrix(Ud.dot(Sd).dot(Vd.T))


def build_fixed_point_matrices(D, c, A, B, rho):

    MM = bmat([[D + rho * A.T.dot(A), None, None],
               [rho * B.T.dot(A), rho * B.T.dot(B), None],
               [A, B, -1.0/rho * identity(B.shape[0])]])

    row = col = data = np.zeros(0)
    empty = coo_matrix((data, (row, col)), shape=(A.shape[1], A.shape[1]))
    NN = bmat([[empty, -rho * A.T.dot(B), -A.T],
               [None, None, -B.T],
               [None, None, -1.0/rho * identity(A.shape[0])]])

    G = spsolve(MM.tocsc(), NN.tocsc())
    r = np.block([-c, np.zeros(B.shape[1]), np.zeros(B.shape[0])])
    b = spsolve(MM.tocsc(), r)

    return G, MM, NN, b


def callback(rk):
    print("rk =", rk)


nx = 6; ny = 3; nz = 2; s = 0.5

D = generate_random_matrix(nx, nx, s, symmetric=True)
A = generate_random_matrix(ny, nx, s)
B = generate_random_matrix(ny, nz, s)
c = np.random.normal(size=nx)

operator = MatrixOperator(D, c, A, B)
u_gmres, status = sp_gmres(operator, operator.myrhs, callback=callback, tol=1e-8)

operator = MatrixOperator(D, c, A, B)
linear_system = LinearSystem(A=operator, b=operator.myrhs)
sol = Gmres(linear_system, tol=1e-8)

**Comment by andrenarchy** [comment] 2019-02-27 14:19
Thanks, I can reproduce it now! Am checking what's wrong...

**Comment by andrenarchy** [comment] 2019-02-27 14:35
I figured it out: the `matvec` operation that you provide can't handle shapes of the form `(n,1)` but only `(n)`. I'm not aware that I can detect this from within krypy but there is an easy fix in your code:

```python
    def _matvec(self, h):
        h = h.reshape(h.shape[0]) # add this line
        Tk = self.__u0 + h
        Tk = self.__G.dot(Tk) + self.__b
        delta_u = h - (Tk-self.__T0)
        return delta_u
```

I'm closing this since I don't think we can do better. I hope it solves your problem – feel free to reopen if it doesn't or if you think we can improve that in krypy!

**Closed by andrenarchy** 2019-02-27 14:35 UTC
